In [1]:
## Acessing elements in a tensor

'''
tesnro[row, column]
'''

import torch

In [17]:
tensor = torch.tensor([[10,20,30],[40,50,60],[70,80,90]])
print(tensor.ndim)
print(tensor.shape)

2
torch.Size([3, 3])


In [4]:
print("Element at (0,1): ", tensor[0,1])

Element at (0,1):  tensor(20)


In [5]:
tensor[0]

tensor([10, 20, 30])

In [6]:
tensor[:,0]

tensor([10, 40, 70])

In [8]:
# Slicing 

print("First two rows : \n", tensor[:2])

First two rows : 
 tensor([[10, 20, 30],
        [40, 50, 60]])


In [9]:
print("First two columns : \n", tensor[:, :2])

First two columns : 
 tensor([[10, 20],
        [40, 50],
        [70, 80]])


In [10]:
print(tensor[1, 1:3])

tensor([50, 60])


In [11]:
# Fancy Indexing

tensor[[0,2],[1,2]]

tensor([20, 90])

In [20]:
tensor[:, 0] = torch.tensor([100,200,300])
print(tensor)

tensor([[100,  20,  30],
        [200,  50,  60],
        [300,  80,  90]])


In [21]:
indices = torch.tensor([0,1])
selected_rows = torch.index_select(tensor, dim=0, index=indices)
print(selected_rows)

tensor([[100,  20,  30],
        [200,  50,  60]])


In [22]:
print(tensor)

tensor([[100,  20,  30],
        [200,  50,  60],
        [300,  80,  90]])


In [23]:
# using tensor with steps

print(tensor[:, ::2])

tensor([[100,  30],
        [200,  60],
        [300,  90]])
