In [ ]:
# data types for tensors

# floating ---> for most deep learning tasks ---> float32, float64, float16
# int -----> for categorical data or indices ---> int32, int64, int8
# boolean ----> used to create mask or logical operation 
# complex number ----> advanced computation  ---> complex64, complex128

# memory consumption - float16 << float32 << float64
# computation - lower precision will be faster on gpu

# numerical precision - float64 is more precise than float32

In [1]:
import torch

In [2]:
default_tensor = torch.tensor([1.5,2.5,3.5])

In [3]:
print(default_tensor.dtype)

torch.float32


In [4]:
float_tensor = torch.tensor([1.5,2.5,3.5], dtype = torch.float64)
print(float_tensor.dtype)

torch.float64


In [5]:
int_tensor = torch.tensor([1.5,2.5,3.5], dtype = torch.int64)
print(int_tensor.dtype)
print(int_tensor)

torch.int64
tensor([1, 2, 3])


In [6]:
boolean_tensor = torch.tensor([True, False, True])
print(boolean_tensor.dtype)

torch.bool


In [8]:
tensor = torch.tensor([1.5,2.5,3.5])
print(tensor)
print(tensor.dtype)

int_tensor = tensor.to(torch.int64) 
print(int_tensor)
print(int_tensor.dtype)

tensor([1.5000, 2.5000, 3.5000])
torch.float32
tensor([1, 2, 3])
torch.int64


In [ ]:
# imapct of data types on memory 

float_32_tensor = torch.ones(1000, dtype=torch.float32)

float_64_tensor = torch.ones(1000, dtype=torch.float64)

#tensor.element_size()
# nelemet()  --> gives the total number of elements in tensor

print("Memory used by float32 tensor : ",float_32_tensor.element_size() * float_32_tensor.nelement())
print("Memory used by float64 tensor : ", float_64_tensor.element_size() * float_64_tensor.nelement())

Memory used by float32 tensor :  4000
Memory used by float64 tensor :  8000
